name: Deploy al VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            if [ ! -d ~/ferre-precios-backend ]; then
              git clone https://${{ secrets.GH_TOKEN }}@github.com/LarissaGuaman1/ferre-precios-backend.git ~/ferre-precios-backend
            fi
            cd ~/ferre-precios-backend
            git pull https://${{ secrets.GH_TOKEN }}@github.com/LarissaGuaman1/ferre-precios-backend.git main
            docker compose down
            docker stop $(docker ps -q) 2>/dev/null || true
            docker compose up -d --build
