name: Deploy FerrePrecios Backend

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Login en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Construir imagen de Docker
        run: docker build -t ghcr.io/larissaguaman1/backend-ferreprecios:latest .

      - name: Publicar la imagen creada
        run: docker push ghcr.io/larissaguaman1/backend-ferreprecios:latest

      - name: Mostrar variables no sensibles
        run: |
          echo "Probando conexión SSH con:"
          echo "Host: ${{ secrets.VPS_HOST }}"
          echo "Usuario: ${{ secrets.VPS_USER }}"
          echo "Puerto: ${{ secrets.VPS_PORT }}"

      - name: Probar SSH en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "Conexión SSH correcta"
            touch ferreprecios.txt

      - name: Pasar archivos desde git al VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          source: "stack.yml,Makefile"
          target: "/home/${{ secrets.VPS_USER }}/ferreprecios-deploy"

      - name: Desplegar stack en el VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/ferreprecios-deploy

            echo "==> Iniciando sesión en GHCR"
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "==> Descargando la imagen del GHCR"
            docker pull ghcr.io/larissaguaman1/backend-ferreprecios:latest

            echo "==> Cargando variables de entorno"
            set -a && . ~/ferre-precios-backend/.env && set +a

            echo "==> Desplegando stack..."
            docker stack deploy -c stack.yml ferreprecios
            
